title: CookieGraph
author: Shaoor Munir

remote_theme: daattali/beautiful-jekyll@5.0.0

navbar-links:
  Source Code: "source"
  Dataset: "dataset"
  Author's home: "https://shaoormunir.com"
 
plugins:
  - jekyll-paginate
  - jekyll-sitemap


url-pretty: "shaoormunir.com"