title: CookieGraph
author: Shaoor Munir

remote_theme: daattali/beautiful-jekyll@5.0.0

navbar-links:
  Publication: "publication"
  Resources:
    - Beautiful Jekyll: "https://beautifuljekyll.com"
    - Learn markdown: "https://www.markdowntutorial.com/"
  Author's home: "https://deanattali.com"
 
plugins:
  - jekyll-paginate
  - jekyll-sitemap


include:
  - _pages

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: minimal

url-pretty: "shaoormunir.com"